// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bikntnhffdszhcrbdnlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpa250bmhmZmRzemhjcmJkbmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODkzMTEsImV4cCI6MjA2MzI2NTMxMX0.4RJjLn1NCU65M3adfYKIiyj886d4UXes4RIK30NHzGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);